project_name: jqplay
before:
  hooks:
    - make clean
    - npm install
builds:
  - main: ./cmd/jqplay/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - "-X 'main.GinMode=release'"
    hooks:
      pre:
        - rm -rf */statik/
        - bin/generate {{ .Target }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
